# Generated by Django 4.0.3 on 2022-03-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'carteiras',
            },
        ),
    ]
