# Generated by Django 4.0.3 on 2022-03-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0002_carteira_resultado_anual_carteira_resultado_diario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='resultado_anual',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='resultado_diario',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='resultado_mensal',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='resultado_semanal',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='resultado_total',
        ),
        migrations.CreateModel(
            name='HistoricoSemanal',
            fields=[
                ('historico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carteiras.historico')),
                ('semana', models.DateField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_semanal', to='carteiras.carteira')),
            ],
            options={
                'db_table': 'historico_semanal',
            },
            bases=('carteiras.historico',),
        ),
        migrations.CreateModel(
            name='HistoricoMensal',
            fields=[
                ('historico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carteiras.historico')),
                ('mes', models.DateField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_mensal', to='carteiras.carteira')),
            ],
            options={
                'db_table': 'historico_mensal',
            },
            bases=('carteiras.historico',),
        ),
        migrations.CreateModel(
            name='HistoricoAnual',
            fields=[
                ('historico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carteiras.historico')),
                ('ano', models.DateField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_anual', to='carteiras.carteira')),
            ],
            options={
                'db_table': 'historico_anual',
            },
            bases=('carteiras.historico',),
        ),
    ]
