# Generated by Django 4.0.3 on 2022-03-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0003_historico_remove_carteira_resultado_anual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicomensal',
            name='carteira',
        ),
        migrations.RemoveField(
            model_name='historicosemanal',
            name='carteira',
        ),
        migrations.DeleteModel(
            name='HistoricoAnual',
        ),
        migrations.DeleteModel(
            name='HistoricoMensal',
        ),
        migrations.DeleteModel(
            name='HistoricoSemanal',
        ),
    ]
