# Generated by Django 4.0.3 on 2022-03-28 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0004_remove_historicomensal_carteira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAnual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ano', models.DateField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_anual', to='carteiras.carteira')),
            ],
            options={
                'db_table': 'historico_anual',
            },
        ),
        migrations.CreateModel(
            name='HistoricoMensal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes', models.DateField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_mensal', to='carteiras.carteira')),
            ],
            options={
                'db_table': 'historico_mensal',
            },
        ),
        migrations.CreateModel(
            name='HistoricoSemanal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('semana', models.DateField(auto_now_add=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_semanal', to='carteiras.carteira')),
            ],
            options={
                'db_table': 'historico_semanal',
            },
        )
    ]
