# Generated by Django 4.0.3 on 2022-03-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0005_historicoanual_historicomensal_historicosemanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoanual',
            name='ano',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicomensal',
            name='mes',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicosemanal',
            name='semana',
            field=models.DateField(),
        ),
    ]
