# Generated by Django 4.0.3 on 2022-03-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0006_delete_historico_alter_historicoanual_ano_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
