# Generated by Django 4.0.3 on 2022-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0007_delete_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='daytrade',
            field=models.BooleanField(default=False),
        ),
    ]
