# Generated by Django 4.0.3 on 2022-03-23 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteiras', '0002_carteira_resultado_anual_carteira_resultado_diario_and_more'),
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_compra', models.DateTimeField()),
                ('data_venda', models.DateTimeField()),
                ('pm_compra', models.FloatField(default=0)),
                ('pm_venda', models.FloatField(default=0)),
                ('quantidade', models.FloatField(default=0)),
                ('custos', models.FloatField(default=0)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.ativo')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carteiras.carteira')),
            ],
            options={
                'db_table': 'operacoes',
            },
        ),
    ]
