# Generated by Django 4.0.3 on 2022-03-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='daytrade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='data_compra',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='data_venda',
            field=models.DateTimeField(null=True),
        ),
    ]
