# Generated by Django 4.0.3 on 2022-03-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_operacao_daytrade_alter_operacao_data_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='data_compra',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='data_venda',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
