# Generated by Django 4.0.3 on 2022-03-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_alter_operacao_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='encerrada',
            field=models.BooleanField(default=False),
        ),
    ]
