# Generated by Django 4.0.3 on 2022-03-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0005_operacao_encerrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='custos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='pm_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='pm_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
