# Generated by Django 4.0.3 on 2022-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0006_alter_operacao_custos_alter_operacao_pm_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='irpf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
