# Generated by Django 4.0.3 on 2022-05-29 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0007_operacao_irpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='data_encerramento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
