# Generated by Django 4.0.3 on 2022-06-19 17:47

from django.db import migrations, models
import django.db.models.deletion
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_alter_ativo_tipo'),
        ('operacoes', '0011_notascorretagem_alter_operacao_custos_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='operacoes.notascorretagem'),
        ),
        migrations.AlterField(
            model_name='notascorretagem',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'NA'), (1, 'ACOES'), (2, 'FUTURO')], default=utils.enums.TipoNota['ACOES']),
        ),
        migrations.AlterUniqueTogether(
            name='operacao',
            unique_together={('ativo', 'pm_compra', 'data_encerramento', 'quantidade', 'nota')},
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='comprovante',
        ),
    ]
