# Generated by Django 4.0.3 on 2022-03-17 00:35

from django.db import migrations, models
import django.db.models.deletion
import utils.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'segmentos',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'setores',
            },
        ),
        migrations.CreateModel(
            name='SubSetor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'subsetores',
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(default=0)),
                ('tipo', models.IntegerField(choices=[(1, 'ACOES'), (2, 'FIIS')], default=utils.enums.TipoAtivo['ACOES'])),
                ('codigo', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=60)),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variacao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.segmento')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.setor')),
                ('subsetor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ativos.subsetor')),
            ],
            options={
                'db_table': 'ativos',
            },
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['codigo'], name='idx_codigo'),
        ),
    ]
