# Generated by Django 4.0.3 on 2022-05-29 14:11

from django.db import migrations, models
import utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'ACOES'), (2, 'FIIS'), (3, 'INDICE')], default=utils.enums.TipoAtivo['ACOES']),
        ),
    ]
