# Generated by Django 4.0.3 on 2022-03-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='SubSetor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('nome', models.CharField(max_length=60)),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acoes.segmento')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acoes.setor')),
                ('subsetor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acoes.subsetor')),
            ],
        ),
    ]
