# Generated by Django 4.0.3 on 2022-03-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0003_acao_variacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='acao',
            index=models.Index(fields=['codigo'], name='acoes_codigo_a900e3_idx'),
        ),
    ]
