# Generated by Django 4.0.3 on 2022-03-16 10:00

import acoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0004_acao_parent_id_acao_acoes_codigo_a900e3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='type',
            field=models.IntegerField(choices=[(1, 'ACOES'), (2, 'FIIS')], default=acoes.models.TipoAtivo['ACOES']),
        ),
    ]
